spring:
  datasource:
    url: jdbc:mysql/localhost:3306/projetmedical

    username: root

    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibertnate:
        dialect: org.hibernate.dialect.MySQL5InnoDialect



